name: Build and Deploy Quarto Site

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install libcurl
      run: |
        sudo apt-get update
        sudo apt-get install -y libcurl4-openssl-dev

    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.1.2'

    - name: Install dependencies
      run: |
        Rscript -e "install.packages(c('openxlsx2', 'purrr', 'janitor', 'dplyr', 'tidyr', 'brew', 'stringr', 'yaml', 'rvest'))"

    - name: Install Quarto
      run: |
        wget https://quarto.org/download/latest/quarto-linux-amd64.deb
        sudo dpkg -i quarto-linux-amd64.deb

    - name: Run pre-render script
      run: |
        Rscript generer_structure_site.R

    - name: Render site
      run: |
        quarto render

    - name: Set correct permissions for the site directory
      run: sudo chmod -R 755 _site

    - name: Move site to docs
      run: |
        mv _site docs

    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4.6.3
      with:
        branch: gh-pages
        folder: docs
