name: Build and Deploy Quarto Site

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.1.2'

    - name: Install dependencies
      run: |
        Rscript -e "install.packages(c('openxlsx2', 'purrr', 'janitor', 'dplyr', 'tidyr', 'brew', 'stringr', 'yaml'))"

    - name: Run pre-render script
      run: |
        Rscript generer_structure_site.R

    - name: Render site
      run: |
        quarto render

    - name: Move site to docs
      run: |
        mv _site docs

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
